# Pytorch 60 Minute Blitz

In [2]:
from __future__ import print_function
import torch

# Basic syntax

## Tensors

Construct an uninitialised random matrix

In [3]:
x = torch.empty(5,3)
print(x)

tensor([[5.8643e+12, 4.5729e-41, 5.8643e+12],
        [4.5729e-41, 3.4716e-37, 0.0000e+00],
        [3.3952e-37, 0.0000e+00, 3.3952e-37],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 3.3991e-37]])


Contruct and random uniform matrix

In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.5766, 0.4046, 0.5142],
        [0.2175, 0.9944, 0.1624],
        [0.0310, 0.8626, 0.3371],
        [0.8674, 0.3976, 0.7439],
        [0.0831, 0.7601, 0.4358]])


In [8]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [22]:
x = torch.tensor([5,3])
print(x)

tensor([5, 3])


Create a tensor based on the properties of another tensor

In [23]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [24]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.2296, -0.6642, -0.4918],
        [ 0.5170,  0.8448,  0.4926],
        [ 0.9822,  0.5813, -0.1513],
        [ 0.9880,  0.9012, -1.3575],
        [ 0.3671,  0.0785,  0.3059]])


In [34]:
x.size() # this is a tuple, and supports all corresponding operations

torch.Size([5, 3])

## Operations

In [48]:
y = torch.rand(5,3)
x+y # can also do torch.add(x,y)

tensor([[ 0.5016, -0.4274,  0.3172],
        [ 0.5794,  1.5979,  1.2394],
        [ 1.0997,  1.2564,  0.3945],
        [ 1.7912,  1.2501, -0.7662],
        [ 0.9481,  0.1016,  0.9356]])

In [51]:
result = torch.empty(5,3)
result = x+y # or torch.add(x, y, out=result)
result

tensor([[ 0.5016, -0.4274,  0.3172],
        [ 0.5794,  1.5979,  1.2394],
        [ 1.0997,  1.2564,  0.3945],
        [ 1.7912,  1.2501, -0.7662],
        [ 0.9481,  0.1016,  0.9356]])

In [52]:
y.add_(x) # add x in-place
print(y)

tensor([[ 0.5016, -0.4274,  0.3172],
        [ 0.5794,  1.5979,  1.2394],
        [ 1.0997,  1.2564,  0.3945],
        [ 1.7912,  1.2501, -0.7662],
        [ 0.9481,  0.1016,  0.9356]])


Any operation that mutates a tensor in-place is post-fixed with an `_`. 

Can use standard NumPy indexing

In [53]:
x[:,1]

tensor([-0.6642,  0.8448,  0.5813,  0.9012,  0.0785])

Resizing of tensors

In [54]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
x.size(), y.size(), z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

In [55]:
x = torch.randn(1)
print(x)
print(x.item()) # .item is a getter method for one-element tensors

tensor([0.6213])
0.6213380098342896


## Torch/NumPy Interconversion

In [56]:
a = torch.ones(5)
b = a.numpy()

In [57]:
a,b

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

In [58]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [59]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

Notice how changing `a` has changed `b`, since the NumPy array and the torch tensor both share the same underlying memory location

In [61]:
import numpy as np

In [62]:
a = np.ones(5)
b = torch.from_numpy(a)

All torch tensors on a CPU, except a CharTensor, support numpy interconversion

If a GPU is available, you can move objects to/from the GPU with code like the following:

In [64]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

# Neural Networks