# Week 1: Tensorflow Basics

In [1]:
import tensorflow as tf

## Build and execute a simple graph

Training neural networks is an intensive task. Neural network training can be done with e.g. `numpy`, but using frameworks such as `tensorflow` allows you to efficiently compute e.g. gradients through computational trees and so on. 

In practice, you'd want to do much of this stuff on a GPU when datasets/networks get sufficiently large. This course will be simple enough to do it all on a CPU.

We first define the graph, which isn't an intensive task. When we execute it, we actually do some computation.

In [2]:
x = tf.constant([1, 2])
y = tf.constant([4, 5])

z = tf.multiply(x, y)

print(z)

Tensor("Mul:0", shape=(2,), dtype=int32)


Returns a tensor. Defining a graph. We are not doing any evaluations in the first instance.

In [3]:
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])

z = tf.multiply(x, y)

sess = tf.Session() # launch a session so we can run the graph. Compiles the graph

print(sess.run(z)) # run the session

sess.close() # always kill sessions when you're done or you'll kill your machine

[ 4 10 18]


Element-wise multiplication

In [4]:
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])

print(x)

Tensor("Const_4:0", shape=(3,), dtype=int32)


In [5]:
output1 = tf.multiply(x, y)

with tf.Session() as sess: # using a with statement will ensure that the session closes when you're done. This is a common structure
    output = sess.run(output1)
    print(output)

[ 4 10 18]


## Load and inspect data

Dataset of children lung function

In [6]:
import pandas as pd
import numpy as np

def load_space_csv_data(file_name):
    df = pd.read_csv(file_name, delim_whitespace=True)
    cols = list(df.columns.values)
    return df, cols

df, cols = load_space_csv_data('lung_function.txt')
print(cols)

['age', 'FEV', 'ht', 'sex', 'smoke']


FEV is a measure of lung function

In [7]:
df.head()

age    FEV    ht  sex  smoke
0    9  1.708  57.0    0      0
1    8  1.724  67.5    0      0
2    7  1.720  54.5    0      0
3    9  1.558  53.0    1      0
4    9  1.895  57.0    1      0

In [8]:
df['age']

0       9
1       8
2       7
3       9
4       9
5       8
6       6
7       6
8       8
9       9
10      6
11      8
12      8
13      8
14      8
15      7
16      5
17      6
18      9
19      9
20      5
21      5
22      4
23      7
24      9
25      3
26      9
27      5
28      8
29      9
       ..
624    15
625    18
626    17
627    15
628    17
629    17
630    16
631    17
632    15
633    15
634    16
635    16
636    15
637    18
638    15
639    16
640    17
641    16
642    16
643    15
644    18
645    15
646    16
647    17
648    16
649    16
650    15
651    18
652    16
653    15
Name: age, Length: 654, dtype: int64

In [9]:
type(df['age'])

pandas.core.series.Series

In [10]:
age = df['age'].values # convert to numpy
print(type(age))

<class 'numpy.ndarray'>


In [11]:
age.dtype

dtype('int64')

In [12]:
age.shape

(654,)

FEV = forced exhalation volume: a measure of how much air somebody can forcibly exhale from their lungs

In [13]:
age_fev = np.column_stack((df['age'].values, df['FEV'].values))
age_fev.shape

(654, 2)

In [14]:
age_fev.dtype

dtype('float64')

## Creating trainable variables

Variable is a trainable node in the graph. Can compute gradients and so on.

In [15]:
a = tf.Variable(2.0, name='a') # 2.0 is the initial value of the object
print(a)

<tf.Variable 'a:0' shape=() dtype=float32_ref>


In [16]:
output2 = tf.add(x, a) # x is some constant defined above
# output2 = tf.add(tf.cast(x, tf.float32), a)
print(output2)

TypeError: Input 'y' of 'Add' Op has type float32 that does not match type int32 of argument 'x'.

Doesn't work because the types don't match

In [17]:
output2 = tf.add(tf.cast(x, tf.float32), a)

In [18]:
with tf.Session() as sess:
    output = sess.run(output2)
    print(output)

FailedPreconditionError: Attempting to use uninitialized value a
	 [[Node: a/read = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](a)]]

Caused by op 'a/read', defined at:
  File "/home/juvid/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/juvid/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/home/juvid/anaconda3/lib/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
  File "/home/juvid/anaconda3/lib/python3.6/asyncio/base_events.py", line 1434, in _run_once
    handle._run()
  File "/home/juvid/anaconda3/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1233, in inner
    self.run()
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 370, in dispatch_queue
    yield self.process_one()
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 346, in wrapper
    runner = Runner(result, future, yielded)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1080, in __init__
    self.run()
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2817, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2843, in _run_cell
    return runner(coro)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3018, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3183, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3265, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-15-14c2145e983c>", line 1, in <module>
    a = tf.Variable(2.0, name='a') # 2.0 is the initial value of the object
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 259, in __init__
    constraint=constraint)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 422, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 80, in identity
    return gen_array_ops.identity(input, name=name)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3264, in identity
    "Identity", input=input, name=name)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value a
	 [[Node: a/read = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](a)]]


### Initializing variables

Variable initialisation in `tensorflow` is a bit odd. The example above fails because tensorflow is trying to read the variable `a` before it has been initialised.  In `tensorflow`, all variables must be explicitly initialized, by running their "initializer" operations

In [19]:
with tf.Session() as sess:
    init_op = tf.global_variables_initializer() # need an initialiser operation
    sess.run(init_op) # run the initialiser for a
    output = sess.run(output2) # then run
    print(output)

[3. 4. 5.]


In [20]:
b = tf.Variable(tf.random_normal([2, 2], stddev=0.1),
                      name="b")

In [21]:
with tf.Session() as sess:
    init_op = tf.global_variables_initializer() # uses a random initialiser. Don't start at 0's, symmetries!
    sess.run(init_op)
    output = sess.run(b)
    print(output)

[[ 0.0419776   0.05267541]
 [-0.04045876  0.05610442]]


### `tf.get_variable`

tf.Variable always makes a new variable, even if you accidentally make two variables with the same name. Can get more variables than you think. `get_variable` is safer. Creates variable if it isn't there. If you try to create it again, get an error, unless you say you want to re-use it.

In [22]:
with tf.variable_scope('layer1'): # scope alters the internal name of the variable, that's all. pre-appends with 'scope'. Nice way to organise variables
    b = tf.get_variable("b", initializer=tf.random_normal([2, 2], stddev=0.1))
    
print(b)

<tf.Variable 'layer1/b:0' shape=(2, 2) dtype=float32_ref>


In [23]:
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    output = sess.run(b)
    print(output)

[[-0.00066561  0.04586932]
 [-0.01083926 -0.0742961 ]]


In [24]:
print(tf.global_variables())

[<tf.Variable 'a:0' shape=() dtype=float32_ref>, <tf.Variable 'b:0' shape=(2, 2) dtype=float32_ref>, <tf.Variable 'layer1/b:0' shape=(2, 2) dtype=float32_ref>]


All variables you have so far in the graph

In [25]:
with tf.variable_scope('layer1'):
    b = tf.get_variable('b', shape=(2, 2), initializer=tf.random_normal_initializer())

ValueError: Variable layer1/b already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "<ipython-input-22-463a0a5f5775>", line 2, in <module>
    b = tf.get_variable("b", initializer=tf.random_normal([2, 2], stddev=0.1))
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3265, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3183, in run_ast_nodes
    if (yield from self.run_code(code, result)):


Throws error because already made a variable with that name. Expected behaviour.

In [26]:
with tf.variable_scope('layer1', reuse=True):
    b = tf.get_variable('b', shape=(2, 2), initializer=tf.random_normal_initializer())

Allows you to re-use variable

In [27]:
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    output = sess.run(b)
    print(output)

[[0.06053761 0.02304289]
 [0.0676597  0.12870142]]


In [28]:
print(tf.global_variables())

[<tf.Variable 'a:0' shape=() dtype=float32_ref>, <tf.Variable 'b:0' shape=(2, 2) dtype=float32_ref>, <tf.Variable 'layer1/b:0' shape=(2, 2) dtype=float32_ref>]


## Placeholders

Entry points into the graph where data can be supplied. This is the input layer to the graph.

In [29]:
c = tf.placeholder(tf.float32, shape=(2,), name='input')
print(c)

Tensor("input:0", shape=(2,), dtype=float32)


In [30]:
with tf.Session() as sess:
    output = sess.run(c)
    print(output)

InvalidArgumentError: You must feed a value for placeholder tensor 'input' with dtype float and shape [2]
	 [[Node: input = Placeholder[dtype=DT_FLOAT, shape=[2], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'input', defined at:
  File "/home/juvid/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/juvid/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/home/juvid/anaconda3/lib/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
  File "/home/juvid/anaconda3/lib/python3.6/asyncio/base_events.py", line 1434, in _run_once
    handle._run()
  File "/home/juvid/anaconda3/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1233, in inner
    self.run()
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2817, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2843, in _run_cell
    return runner(coro)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3018, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3183, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3265, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-29-0ee0369241bb>", line 1, in <module>
    c = tf.placeholder(tf.float32, shape=(2,), name='input')
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1735, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4925, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/juvid/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'input' with dtype float and shape [2]
	 [[Node: input = Placeholder[dtype=DT_FLOAT, shape=[2], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]


Error because the placeholder hasn't got a value. It can't be evaluated.

In [31]:
feed_dict = {c: np.array([3, 4])} # this is how to set a placeholder to some data

with tf.Session() as sess:
    output = sess.run(c, feed_dict=feed_dict)
    print(output)

[3. 4.]


## Some more operations

All operations in a graph should be symbolic operations so it can be optimized at runtime. Standard operators are overloaded.

In [32]:
mat_inv = tf.matrix_inverse(b)
mat_vec_multiply = tf.matmul(mat_inv, tf.expand_dims(c, axis=1))
print(mat_vec_multiply)

Tensor("MatMul:0", shape=(2, 1), dtype=float32)


Annoying extra dimension

In [33]:
squeezed = tf.squeeze(mat_vec_multiply)
print(squeezed)

Tensor("Squeeze:0", shape=(2,), dtype=float32)


Analogous to numpy squeeze

In [34]:
feed_dict = {c: np.array([1, 1])}

with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    output = sess.run([squeezed, mat_inv], feed_dict=feed_dict)
    print(output[0])
    print(output[1])

[57.821457 16.021023]
[[21.40829  36.413166]
 [12.76862   3.252403]]
